use color_eyre::eyre::bail;
use color_eyre::{Report, Result};
use serde::{Deserialize, Serialize};
use strum_macros::{AsRefStr, Display, EnumIter, EnumString};


pub type KeyCodes = Vec<KeyCode>;

#[derive(PartialOrd, EnumIter, EnumString, AsRefStr, Display, Eq, Hash, PartialEq, Copy, Clone, Debug, Serialize, Deserialize, )]
pub enum KeyCode {
    None,
    RESET_BTN,
    SWITCH_MODE_BTN,
    RELEASE_ALL,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_10,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,

    KEY_ZENKAKUHANKAKU,
    KEY_102ND,
    KEY_F11,
    KEY_F12,
    KEY_RO,
    KEY_KATAKANA,
    KEY_HIRAGANA,
    KEY_HENKAN,
    KEY_KATAKANAHIRAGANA,
    KEY_MUHENKAN,
    KEY_KPJPCOMMA,
    KEY_KPENTER,
    KEY_RIGHTCTRL,
    KEY_KPSLASH,
    KEY_SYSRQ,
    KEY_RIGHTALT,
    KEY_LINEFEED,
    KEY_HOME,
    KEY_UP,
    KEY_PAGEUP,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_MACRO,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_POWER,
    /* SC System Power Down */
    KEY_KPEQUAL,
    KEY_KPPLUSMINUS,
    KEY_PAUSE,
    KEY_SCALE,
    /* AL Compiz Scale  = Expose */
    KEY_KPCOMMA,
    KEY_HANGEUL,
    KEY_HANJA,
    KEY_YEN,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_COMPOSE,

    KEY_STOP,
    /* AC Stop */
    KEY_AGAIN,
    KEY_PROPS,
    /* AC Properties */
    KEY_UNDO,
    /* AC Undo */
    KEY_FRONT,
    KEY_COPY,
    /* AC Copy */
    KEY_OPEN,
    /* AC Open */
    KEY_PASTE,
    /* AC Paste */
    KEY_FIND,
    /* AC Search */
    KEY_CUT,
    /* AC Cut */
    KEY_HELP,
    /* AL Integrated Help Center */
    KEY_MENU,
    /* Menu  = show menu */
    KEY_CALC,
    /* AL Calculator */
    KEY_SETUP,
    KEY_SLEEP,
    /* SC System Sleep */
    KEY_WAKEUP,
    /* System Wake Up */
    KEY_FILE,
    /* AL Local Machine Browser */
    KEY_SENDFILE,
    KEY_DELETEFILE,
    KEY_XFER,
    KEY_PROG1,
    KEY_PROG2,
    KEY_WWW,
    /* AL Internet Browser */
    KEY_MSDOS,
    /* AL Terminal Lock/Screensaver */
    KEY_SCREENLOCK,
    KEY_ROTATE_DISPLAY,
    KEY_CYCLEWINDOWS,
    KEY_MAIL,
    KEY_BOOKMARKS,
    /* AC Bookmarks */
    KEY_COMPUTER,
    KEY_BACK,
    /* AC Back */
    KEY_FORWARD,
    /* AC Forward */
    KEY_CLOSECD,
    KEY_EJECTCD,
    KEY_EJECTCLOSECD,
    KEY_NEXTSONG,
    KEY_PLAYPAUSE,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
    KEY_RECORD,
    KEY_REWIND,
    KEY_PHONE,
    /* Media Select Telephone */
    KEY_ISO,
    KEY_CONFIG,
    /* AL Consumer Control Configuration */
    KEY_HOMEPAGE,
    /* AC Home */
    KEY_REFRESH,
    /* AC Refresh */
    KEY_EXIT,
    /* AC Exit */
    KEY_MOVE,
    KEY_EDIT,
    KEY_SCROLLUP,
    KEY_SCROLLDOWN,
    KEY_KPLEFTPAREN,
    KEY_KPRIGHTPAREN,
    KEY_NEW,
    /* AC New */
    KEY_REDO,
    /* AC Redo/Repeat */
    //Mouse
    MOUSE_LEFT,
    MOUSE_RIGHT,
    MOUSE_MIDDLE,
    MOUSE_SIDE,
    MOUSE_EXTRA,
    MOUSE_FORWARD,
    MOUSE_BACK,
    MOUSE_TASK,
}